# Generated by Django 3.2.3 on 2021-06-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('titular', models.TextField()),
                ('epigrafe', models.TextField()),
                ('publicar', models.BooleanField(default=False)),
                ('CategoriaNoticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorianoticia')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaImagen',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('url_imagen', models.TextField()),
                ('Noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaDetalle',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('Noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
            ],
        ),
    ]
