# Generated by Django 3.2.4 on 2021-06-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210621_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(default='xd'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NoticiaDetalle',
        ),
    ]
