# Generated by Django 3.2.3 on 2021-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_noticiamoderacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
